import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  const handleLogin = () => {
    alert('yey');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <button onClick={handleLogin} className={styles.card}>
            <h2>Login with google</h2>
            <p>User carsu account or else go fucking die</p>
          </button>
        </div>
      </main>
    </div>
  );
}
