import Head from 'next/head';
import Login from '../components/login';

export default function Home() {
  const handleLogin = () => {
    alert('yey');
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Login />
    </div>
  );
}
