import Head from 'next/head';

export default function Home() {
  const handleLogin = () => {
    alert('yey');
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <button onClick={handleLogin}>
            <h2>Login with google</h2>
            <p>User carsu account or else go fucking die</p>
          </button>
        </div>
      </main>
    </div>
  );
}
